### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by IvBaranov** [IvBaranov/RxBluetooth#1]
- [x] sending and receiving data
- [x] profiles
- [ ] manage connection as client/server
- [ ] ble?

**Comment by moritzrupp** [comment]
Hi @IvBaranov,

I just found your RxBluetooth library and I'm planning to use it in my project. The most interesting thing is the send and receiving of data. Can you tell me something about your plans? In the meantime I will have a look at this as well, but I pretty new to Rx.

Thanks
Moritz

**Comment by IvBaranov** [comment]
Hi @moritzrupp,

I will have some free time to research or implement this weekend. I will keep you in touch.

**Comment by moritzrupp** [comment]
Hello @qwildz ,

this looks great! Thanks for your contribution as well.

**Comment by qwildz** [comment]
@moritzrupp You're welcome, glad it helps!
And thanks @IvBaranov for this repo :smiley:
