### ISSUE TITLE
enableBluetooth() with null adapters cause null pointer exeption. 

### ISSUE THREAD

**Issue by asmic** [IvBaranov/RxBluetooth#12]
if (!rxBluetooth.isBluetoothAvailable()) {
      // to enable blutooth via startActivityForResult()
      rxBluetooth.enableBluetooth(this, REQUEST_ENABLE_BT);
    } else {
     // makeFun
    }
For device that not support BT at all this function cause NPE. 

You have to check if mBluetoothAdapter is not a null object inside enableBluetooth or add additional functions to check if BT is available at all.

**Comment by IvBaranov** [comment]
Since `BluetoothAdapter.getDefaultAdapter()` returned `null` in `rxBluetooth.isBluetoothAvailable()` method you must not use any other methods related to working Bluetooth device, because from this moment you are sure that Bluetooth is not supported on this hardware platform.

**Comment by asmic** [comment]
You have right, but you have to change the readme file. I just follow up step by step instruction.

> Check if bluetooth is currently enabled and ready for use:
> 
> if  (!rxBluetooth.isBluetoothAvailable()) {
>   // to enable blutooth via startActivityForResult()
>   rxBluetooth.enableBluetooth(this, REQUEST_ENABLE_BT);
> }

I think it should be: 
```
if (!rxBluetooth.isBluetoothAvailable()) {
      // bluetooth is not available
      return;
    }else if (!rxBluetooth.isBluetoothEnabled()){
      // to enable blutooth via startActivityForResult()
      rxBluetooth.enableBluetooth(this, REQUEST_ENABLE_BT);
    } else {
      // you can use your bt device
}
```

**Comment by IvBaranov** [comment]
Sorry, now I see.
