### ISSUE TITLE
Support for rxjava2

### ISSUE THREAD

**Issue by vekexasia** [IvBaranov/RxBluetooth#15]
Hello,

are you planning to add support for rxjava2?

**Comment by IvBaranov** [comment]
I would like, however I did not touch _rxjava2_ yet. It is definitely will take some time.

**Comment by ghost** [comment]
Hi @IvBaranov , I cloned the project and removed the RxJava and then implemented the RxJava2...
I'm having a bit of troubles creating Pull request, or better say, I don't know exactly how to... Are you willing to help out, maybe you'll like it.

**Comment by IvBaranov** [comment]
@plutondev hi, check [this](https://gist.github.com/MarcDiethelm/7303312) or [this](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) tips.

I will prepare separate branches for rxjava-v1 and rxjava-v2 later.

**Comment by ghost** [comment]
thanks for the links, will wait for the weekend to go trough that.

**Comment by IvBaranov** [comment]
b71806b4fd62275e3d0e55fd2efa7f610be47472

**Comment by onivas** [comment]
I see, rxjava2 merge has been done, why this issue is still open? is there still something missing?

**Comment by IvBaranov** [comment]
I wanted to close issue once version bumped from `SNAPSHOT` to `2.0`. I will make it shortly.

**Comment by ghost** [comment]
Hi Ivan,

maybe I'm doing something wrong, but if I copy/paste this link: compile 'com.github.ivbaranov:rxbluetooth2:2.0.0'
into my gradle, I get Unathorized code.

here is a full error after I try to clean project:

> Error:Could not resolve all files for configuration ':app:debugCompileClasspath'.
> > Could not resolve com.github.ivbaranov:rxbluetooth2:2.0.0.
>   Required by:
>       project :app
>    > Could not resolve com.github.ivbaranov:rxbluetooth2:2.0.0.
>       > Could not get resource 'https://jitpack.io/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom'.
>          > Could not GET 'https://jitpack.io/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by IvBaranov** [comment]
@plutondev it takes some time while Jitpack compile artifact from source for the first time. Consider  using `jcenter()` or `mavenCentral()` maven instead.
