### ISSUE TITLE
Using lib from android service

### ISSUE THREAD

**Issue by pierreroth64** [IvBaranov/RxBluetooth#16]
Hi,

I plan to use your RxBluetooth lib from an android service (called with [startService](https://developer.android.com/reference/android/content/Context.html#startService(android.content.Intent)), ie: long running service) to continuously talk to connected devices.

I think I can pass a `Service.this` to the `RxBluetooth` constructor as Android services inherit from `Context`.

However I can see a `unsubscribeInUiThread` call (which depends on `AndroidSchedulers`) that may cause trouble as the RxBluetooth methods will be called from the service code.

Do you have any suggestion on how to deal with limitation and make the lib available on service side ?

Thanks a lot!

**Comment by IvBaranov** [comment]
Could you be more specific in what limitations?
Added example of service usage in af8470a15bec14983025792ddca1cfd2f195a063.

**Comment by pierreroth64** [comment]
Thanks for your example. I tought that calling this `unsubscribeInUiThread(...)` call would have been problematic when called from an android service. That's not the case.
