### ISSUE TITLE
Exception: Read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by ghost** [IvBaranov/RxBluetooth#22]
Hi, I'am trying to send data to device when user click a button. First time everything is OK. But, when I click the button second time, I receive IOException exception with message "Read failed, socket might closed or timeout, read ret: -1". The problem is in bluetoothSocket.connect(); function. It's android problem after android 4.2.

**Comment by IvBaranov** [comment]
Seems here is the solution https://stackoverflow.com/a/25647197/2459628

**Comment by IvBaranov** [comment]
#25 #26

**Comment by amon-shadow** [comment]
By adding filter action my problem resolved

     // Register for broadcasts when a device is discovered
        IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(BluetoothDevice.ACTION_FOUND);
        intentFilter.addAction(BluetoothAdapter.ACTION_DISCOVERY_STARTED);
        intentFilter.addAction(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);
        registerReceiver(mReceiver, intentFilter);
