### ISSUE TITLE
Problem with importing module

### ISSUE THREAD

**Issue by nikoladjukic** [IvBaranov/RxBluetooth#23]
Hello,

I have added dependancy for RxBluetooth, but I am getting an error:
Error:(22, 13) Failed to resolve: com.github.ivbaranov:rxbluetooth2:2.0.0-SNAPSHOT
I have attached my gradle file.

Thank you

[app_build_gradle.txt](https://github.com/IvBaranov/RxBluetooth/files/1168037/app_build_gradle.txt)

**Comment by IvBaranov** [comment]
RxBluetooth2 is currently published as a snapshot, so make sure you have added the Sonatype snapshots repository url:

```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
```
