### ISSUE TITLE
(0.1.6) observeConnectDevice working on the main thread 

### ISSUE THREAD

**Issue by pentarex** [IvBaranov/RxBluetooth#25]
Hi I am using version 0.1.6<br>
And every time I try to connect to some device, the app hangs and it shows how many frames were skipped.<br>
```kotlin
rxBluetooth.observeConnectDevice(btDevice, uuid)
                .subscribeOn(AndroidSchedulers.mainThread())
                .observeOn(Schedulers.computation())
                .subscribe({
                    println(btDevice.name)
                    bluetoothConnection = BluetoothConnection(it)
                    busProvider.post(RxBluetoothBusEvent().BluetoothDeviceConnected())
                },{
                    it.printStackTrace()
                    busProvider.post(RxBluetoothBusEvent().Exception(it))
                })
```
This is my code. Am I doing something wrong or its a bug in the library?<br>
Thanks

**Comment by IvBaranov** [comment]
First of all, any non-ui work should be done in a thread other than main thread.
Secondly, is constructor of `BluetoothConnection` class throwing any exceptions?

**Comment by pentarex** [comment]
Yeah sorry, Ive saw the example from your README.md how to connect to device (only changed from io to computation, for the sake of the test). 

BluetoothConnection is not throwing exception if the socket is open, otherwise if there is already a connection to the device which I am trying to connect, it says
```bash
09-29 10:45:29.276 9022-9022/at.co.pjm.abp I/Choreographer: Skipped 391 frames!  The application may be doing too much work on its main thread.
09-29 10:45:29.287 9022-9022/at.co.pjm.abp I/System.out: read failed, socket might closed or timeout, read ret: -1
```

**Comment by IvBaranov** [comment]
To close connection properly, input/output streams and socket should be closed.
So `BluetoothConnection.closeConnection()` should be called when you are done, in `onDestroy()` for example.

See [also](https://stackoverflow.com/a/3039807/2459628).

**Comment by pentarex** [comment]
OK this answers #26 but still not sure if I am doing something wrong, because even if I remove the subscribeOn then still when calling BluetoothConnection is running on the main thread, and wondering is this my fault somehow or?

**Comment by IvBaranov** [comment]
`subscribeOn()` should not have been removed but the thread should be replaced in favour of `computation` thread, for example.

By removing `subscribeOn()` you use default thread, the thread that declares the subscribe() which is main thread.

**Comment by pentarex** [comment]
ok thank you.
