### ISSUE TITLE
JavaDocs: 404 Errors

### ISSUE THREAD

**Issue by commonsguy** [IvBaranov/RxBluetooth#27]
The [initial page of the JavaDocs](http://ivbaranov.github.io/RxBluetooth/javadoc2/) comes up fine. If you click on any of the packages or classes, though, you get a 404 for each of them.

**Comment by IvBaranov** [comment]
@commonsguy thanks for noticing.

**Comment by IvBaranov** [comment]
`BtPredicate` is still missing, I will generate up-to-date JavaDoc shortly.

**Comment by IvBaranov** [comment]
Fixed.
