### ISSUE TITLE
Consider Dropping ACCESS_FINE_LOCATION

### ISSUE THREAD

**Issue by commonsguy** [IvBaranov/RxBluetooth#28]
We need *a* location permission to use Bluetooth. The manifest for the library, though, requests both. This means that apps need to explicitly remove `ACCESS_FINE_LOCATION` if the developer does not want it, using:

```xml
  <uses-permission
    android:name="android.permission.ACCESS_FINE_LOCATION"
    tools:node="remove" />
```

I am uncertain what benefit there is in the library declaring both permissions, so I am hoping that you will consider only including `ACCESS_COARSE_LOCATION`, which is sufficient for Bluetooth MAC address access, at least based on my tests to date.

Thanks for considering this!

**Comment by IvBaranov** [comment]
You are absolutely right. Thanks for contributing!
Fixed in 459211e7718c4f3311a7435affc0aa3146d2aa67
