### ISSUE TITLE
Artifact Missing, or Documentation Problem

### ISSUE THREAD

**Issue by commonsguy** [IvBaranov/RxBluetooth#30]
https://github.com/IvBaranov/RxBluetooth#download

This says that the current version is `2.0.0`, which is new; it had been `2.0.0-SNAPSHOT` previously. However, I cannot find `2.0.0` anywhere:

- It's not in [the snapshots repo](https://oss.sonatype.org/content/repositories/snapshots/com/github/ivbaranov/rxbluetooth2/), the way the documentation suggests

- It's not in [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ccom.github.ivbaranov)

- JCenter's search is seriously messed up, so I don't know if it is there, but `jcenter()` isn't finding it in a Gradle build, even with `--refresh-dependencies`:

```
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.github.ivbaranov:rxbluetooth2:2.0.0.
  Searched in the following locations:
      file:/opt/android-sdk-linux/extras/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      file:/opt/android-sdk-linux/extras/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
      file:/opt/android-sdk-linux/extras/google/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      file:/opt/android-sdk-linux/extras/google/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
      file:/opt/android-sdk-linux/extras/android/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      file:/opt/android-sdk-linux/extras/android/m2repository/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
      https://dl.google.com/dl/android/maven2/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      https://dl.google.com/dl/android/maven2/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
      https://jcenter.bintray.com/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      https://jcenter.bintray.com/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
      https://oss.sonatype.org/content/repositories/snapshots/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.pom
      https://oss.sonatype.org/content/repositories/snapshots/com/github/ivbaranov/rxbluetooth2/2.0.0/rxbluetooth2-2.0.0.jar
  Required by:
      project :app
```

I am not certain if the documentation is citing the wrong artifact version (or the wrong artifact location) or if I am just totally screwing this up somehow.

Thanks!

**Comment by IvBaranov** [comment]
Sorry for this mess, I guess I had really bad day when 2.0.0 was releasing.

Talking about JCenter, I made a research and looks like I forgot to sync repository to JCenter. The artifact id of 2.0.0 version is new, so it appeared as a separate project, so I merged them and sent a ticket for syncing.
Here is [Bintray page](https://bintray.com/ivbaranov/maven/RxBluetooth). Everything looks ok.

According to lack of 2.0.0 release artifact in the snapshots repository it is pretty much ok, I guess.

I have no answer about Maven Central for now, I will try to manage with it tomorrow.

So, right now I can suggest only a temporary solution using personal maven:
```
allprojects {
  repositories {
    ...
    maven { url 'https://dl.bintray.com/ivbaranov/maven' }
  }
}

dependencies {
  compile 'com.github.ivbaranov:rxbluetooth2:2.0.0'
}
```

or using Jitpack:
```
allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}

dependencies {
  compile 'com.github.IvBaranov:RxBluetooth:2.0.0'
}
```

**Comment by commonsguy** [comment]
Once Bintray syncs, everything should be OK, presumably. At the moment, I don't see anything related to this project, just the older one:

https://jcenter.bintray.com/com/github/ivbaranov/

I'll check back tomorrow and see if JCenter is happier.

Thanks for your help!

**Comment by IvBaranov** [comment]
[Maven Central](https://oss.sonatype.org/content/repositories/releases/com/github/ivbaranov/rxbluetooth2/) - fixed.

[Maven Central snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/github/ivbaranov/rxbluetooth2/) - added `2.0.1-SNAPSHOT`.

JCenter - still no luck. Bintray link to JCenter has been approved about 7 hours ago, but the package did not sync.

**Comment by commonsguy** [comment]
Yes, if I add `mavenCentral()` to Gradle, the artifact can be found. Many thanks!

I'm leaving this issue open in case you wanted to use it for tracking the JCenter status.

**Comment by IvBaranov** [comment]
Starting with `2.0.1` version the problem with [jcenter](https://jcenter.bintray.com/com/github/ivbaranov/rxbluetooth2/) is fixed.
