### ISSUE TITLE
Add Wrapper Method For enable()

### ISSUE THREAD

**Issue by commonsguy** [IvBaranov/RxBluetooth#31]
In an Android mobile device scenario, we should use `enableBluetooth()` on `RxBluetooth`, which works nicely. However, in an Android Things environment, that's not an option: the enable-Bluetooth activity doesn't even exist.

On an Android Thing, we're supposed to use `enable()` directly. However, `RxBluetooth` doesn't wrap that method, so we have to get our own `BluetoothAdapter` for that. This isn't a huge issue, but since you have other pass-through wrapper methods (e.g., `isEnabled()`), it would be handy if you offered an `RxBluetooth` wrapper for `enable()` (and perhaps `disable()`).

If you'd like me to make this change and send you a pull request, just let me know.

Thanks for considering this!

**Comment by IvBaranov** [comment]
Thanks!
