### ISSUE TITLE
observeStringStream() generating extra response

### ISSUE THREAD

**Issue by mrbythatmuch** [IvBaranov/RxBluetooth#32]
I'm getting "" strings after each string/message is received.  I've created an HCI log to confirm my bluetooth device was sending the message format I expected.  It is sending a single JSON response that terminates ends with }\r\n
Inspecting the code for observeStringStream() it calls observeStringStream with \r,\n as the delimiter.  The onNext is emitting when the first delimiter is found instead of waiting to match both.  The result is the buffer is cleared then emit is called again when it reads the next byte which will match the \n.  This time the buffer is empty because it was just cleared so the then in emit() line 160 is called sending a blank "" string.

If the delimiter is \r\n then the behavior I was expecting was just the string in my case the json {} should be returned correct?  

`          @Override public void onNext(Byte b) {
            boolean found = false;
            for (int d : delimiter) {
              if (b == d) {
                found = true;
                break;
              }
            }

![image](https://user-images.githubusercontent.com/12568782/34196513-472736b6-e517-11e7-90d4-7031177860e9.png)
`

**Comment by IvBaranov** [comment]
Managed to emit only after received delimiters list matches the provided ones.
Please, take a look.

Snapshot version with current changes is available at:
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
```
```
compile 'com.github.ivbaranov:rxbluetooth2:2.0.2-SNAPSHOT'
```
