### ISSUE TITLE
Observing connection failing

### ISSUE THREAD

**Issue by therealmoronto** [IvBaranov/RxBluetooth#36]
Every time I try to connect to any Android device and subscribe Observable to wait for bytes from connection it fails with IOException: "read failed, socket might closed or timeout, read ret: -1".

**Comment by Kurisasa** [comment]
Hi @toruk0109 

Did you win? BluetoothConnection class is throwing me the same exception.

**Comment by therealmoronto** [comment]
> Hi @toruk0109
> 
> Did you win? BluetoothConnection class is throwing me the same exception.

Hey! I didn't :( And I left behind Development for Android and iPhone forever
