### ISSUE TITLE
Version 2.1.0 unavailable

### ISSUE THREAD

**Issue by filipwiech** [IvBaranov/RxBluetooth#55]
Hi,

It seems that version 2.1.0 is not available, despite being shown in the README:
`compile 'com.github.ivbaranov:rxbluetooth2:2.1.0'`

**Comment by IvBaranov** [comment]
Sorry, release build has been broken and there was an error while uploading artifacts. Reverted to `2.0.4` as last available version.

**Comment by IvBaranov** [comment]
`2.1.0` is up. Keep in mind that `2.1.0+` are AndroidX versions.
