### ISSUE TITLE
gradle-license-plugin not found RxBluetooth2 license

### ISSUE THREAD

**Issue by NunciosChums** [IvBaranov/RxBluetooth#57]
https://github.com/jaredsburrows/gradle-license-plugin library is not found RxBluetooth's license.
But I don't know why.

![device-2019-01-30-130054](https://user-images.githubusercontent.com/1233318/51957517-51095480-248f-11e9-8ab3-8ade86c505d1.jpg)

another library is ok
![device-2019-01-30-130438](https://user-images.githubusercontent.com/1233318/51957597-a6ddfc80-248f-11e9-9a3a-66137d29ba25.jpg)

**Comment by IvBaranov** [comment]
There were some publish issues. `2.1.0` version should work fine now.
Keep in mind that `2.1.0+` are AndroidX versions.

**Comment by NunciosChums** [comment]
`2.1.0` has same problem. `licenseReleaseReport`, `licenseDebugReport` is same result.

**Comment by vanniktech** [comment]
I think the problem may lie in the POM file.

**Comment by IvBaranov** [comment]
Guess so. As the `.pom` in `mavenCentral` is different from `jcenter`.

So a temporary workaround is using `mavenCentral` until I fix bintray-release

**Comment by NunciosChums** [comment]
ok. thank you.
