### ISSUE TITLE
Suggestion: add btAdapter.getBondedDevices()

### ISSUE THREAD

**Issue by Jaykob** [IvBaranov/RxBluetooth#6]
Hi,
thanks for your nice work! 
I have a pretty basic suggestion though:
Adding a wrapper for `BluetoothAdapter.getBondedDevices()` would be very nice, as this should be the preferred way of connecting to a device which has been discovered and connected before.

**Comment by IvBaranov** [comment]
Hi,
thank you.

I was not sure if delegating `getBoundedDevices()` would be helpful.
So by adding this method to RxBluetooth:
```
public Set<BluetoothDevice> getBondedDevices() {
    return mBluetoothAdapter.getBondedDevices();
}
```
Getting devices that were discovered and connected before will look like:
```
rxBluetooth.observeBluetoothState()
      .observeOn(AndroidSchedulers.mainThread())
      .subscribeOn(Schedulers.computation())
      .filter(Action.isEqualTo(BluetoothAdapter.STATE_ON))
      .subscribe(new Action1<Integer>() {
        @Override public void call(Integer integer) {
            Set<BluetoothDevice> boundedDevices = rxBluetooth.getBondedDevices();
            //...
        }
      });
```
Did you mean this?

**Comment by Jaykob** [comment]
Exactly!
This would save me from discovering the same devices over and over again, which is time and power consuming. The `getBondedDevices()` method returns immediately and thereby speeds up the process of connecting.

**Comment by IvBaranov** [comment]
Done.

**Comment by Jaykob** [comment]
Wow, that was quick! Thank you!
