### ISSUE TITLE
Beacon.getDistance totally returns different values on different devices

### ISSUE THREAD

**Issue by dominolog** [IvBaranov/RxBluetooth#60]
I wrote an app using this library to show nearby beacons and distances between the device and beacon. The problem is even having two different phones running the same app and couple of beacons around I can see the distance values differs significantly. 
I use 
Becon.getDistance
method.
Any suggestions?

**Comment by IvBaranov** [comment]
Guess you are calculating distance using BT signal strength. The key to this problem is that different devices are build using different BT hw modules. In order to make you distance measurements similar different formulas for each hw module should be used.
