### ISSUE TITLE
Missing location permission for action found since Android 6.0

### ISSUE THREAD

**Issue by psabata** [IvBaranov/RxBluetooth#7]
Since Android 6.0 location permission (`ACCESS_COARSE_LOCATION` or `ACCESS_FINE_LOCATION`) is required to accept `BluetoothDevice.ACTION_FOUND` event. See [Android 6.0 Changes](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id) for reference.  Might be worth to mention that in documentation. Thanks for the library.

**Comment by IvBaranov** [comment]
Thanks, I will add `ACCESS_COARSE_LOCATION` permission ASAP.
